!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/cmf
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Sebastian Domas
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/cmf",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/cmf"]=t(e._Highcharts,e._Highcharts.SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(e,t){return function(){"use strict";var r,n={512:function(e){e.exports=t},944:function(t){t.exports=e}},o={};function i(e){var t=o[e];if(void 0!==t)return t.exports;var r=o[e]={exports:{}};return n[e](r,r.exports,i),r.exports}i.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(t,{a:t}),t},i.d=function(e,t){if(Array.isArray(t))for(var r=0;r<t.length;){var n=t[r++],o=t[r++];i.o(e,n)?0===o&&r++:0===o?Object.defineProperty(e,n,{enumerable:!0,value:t[r++]}):Object.defineProperty(e,n,{enumerable:!0,get:o})}else for(var n in t)i.o(t,n)&&!i.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},i.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)};var u={};i.d(u,{default:function(){return y}});var s=i(944),a=i.n(s),c=i(512),l=i.n(c),p=(r=function(e,t){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)},function(e,t){function n(){this.constructor=e}r(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}),f=l().seriesTypes.sma,h=function(e){function t(){var t=null!==e&&e.apply(this,arguments)||this;return t.nameBase="Chaikin Money Flow",t}return p(t,e),t.prototype.isValid=function(){var e,t=this.chart,r=this.options,n=this.linkedParent,o=this.volumeSeries||(this.volumeSeries=t.get(r.params.volumeSeriesID)),i=(null==(e=null==n?void 0:n.pointArrayMap)?void 0:e.length)===4;function u(e){return e.dataTable.rowCount>=r.params.period}return!!(n&&o&&u(n)&&u(o)&&i)},t.prototype.getValues=function(e,t){if(this.isValid())return this.getMoneyFlow(e.xData,e.yData,this.volumeSeries.getColumn("y"),t.period)},t.prototype.getMoneyFlow=function(e,t,r,n){var o,i,u=t.length,s=[],a=[],c=[],l=[],p=-1,f=0,h=0;function y(e,t){var r=e[1],n=e[2],i=e[3];return null!==t&&null!==r&&null!==n&&null!==i&&r!==n?(i-n-(r-i))/(r-n)*t:(p=o,null)}if(n>0&&n<=u){for(o=0;o<n;o++)s[o]=y(t[o],r[o]),f+=r[o],h+=s[o];for(a.push(e[o-1]),c.push(o-p>=n&&0!==f?h/f:null),l.push([a[0],c[0]]);o<u;o++)s[o]=y(t[o],r[o]),f-=r[o-n],f+=r[o],h-=s[o-n],h+=s[o],i=[e[o],o-p>=n?h/f:null],a.push(i[0]),c.push(i[1]),l.push([i[0],i[1]])}return{values:l,xData:a,yData:c}},t.defaultOptions=(0,s.merge)(f.defaultOptions,{params:{index:void 0,volumeSeriesID:"volume"}}),t}(f);l().registerSeriesType("cmf",h);var y=a();return u.default}()});