!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/disparity-index
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highstock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Rafał Sebestjański
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/disparity-index",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/disparity-index"]=t(e._Highcharts,e._Highcharts.SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(e,t){return function(){"use strict";var r,n={512:function(e){e.exports=t},944:function(t){t.exports=e}},i={};function a(e){var t=i[e];if(void 0!==t)return t.exports;var r=i[e]={exports:{}};return n[e](r,r.exports,a),r.exports}a.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(t,{a:t}),t},a.d=function(e,t){if(Array.isArray(t))for(var r=0;r<t.length;){var n=t[r++],i=t[r++];a.o(e,n)?0===i&&r++:0===i?Object.defineProperty(e,n,{enumerable:!0,value:t[r++]}):Object.defineProperty(e,n,{enumerable:!0,get:i})}else for(var n in t)a.o(t,n)&&!a.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},a.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)};var o={};a.d(o,{default:function(){return y}});var s=a(944),p=a.n(s),u=a(512),c=a.n(u),f=(r=function(e,t){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)},function(e,t){function n(){this.constructor=e}r(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}),d=c().seriesTypes.sma,h=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return f(t,e),t.prototype.init=function(){var e=arguments,t=e[1].params,r=t&&t.average?t.average:void 0;this.averageIndicator=c().seriesTypes[r]||d,this.averageIndicator.prototype.init.apply(this,e)},t.prototype.calculateDisparityIndex=function(e,t){return(0,s.correctFloat)(e-t)/t*100},t.prototype.getValues=function(e,t){var r=t.index,n=e.xData,i=e.yData,a=i?i.length:0,o=[],p=[],u=[],c=this.averageIndicator,f=(0,s.isArray)(i[0]),d=c.prototype.getValues(e,t),h=d.yData,y=n.indexOf(d.xData[0]);if(h&&0!==h.length&&(0,s.defined)(r)&&!(i.length<=y)){for(var g=y;g<a;g++){var l=this.calculateDisparityIndex(f?i[g][r]:i[g],h[g-y]);o.push([n[g],l]),p.push(n[g]),u.push(l)}return{values:o,xData:p,yData:u}}},t.defaultOptions=(0,s.merge)(d.defaultOptions,{params:{average:"sma",index:3},marker:{enabled:!1},dataGrouping:{approximation:"averages"}}),t}(d);(0,s.extend)(h.prototype,{nameBase:"Disparity Index",nameComponents:["period","average"]}),c().registerSeriesType("disparityindex",h);var y=p();return o.default}()});