!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/dpo
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Wojciech Chmiel
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(t._Highcharts,t._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/dpo",["highcharts/highcharts"],function(t){return e(t,t.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/dpo"]=e(t._Highcharts,t._Highcharts.SeriesRegistry):t.Highcharts=e(t.Highcharts,t.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(t,e){return function(){"use strict";var r,n={512:function(t){t.exports=e},944:function(e){e.exports=t}},o={};function i(t){var e=o[t];if(void 0!==e)return e.exports;var r=o[t]={exports:{}};return n[t](r,r.exports,i),r.exports}i.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return i.d(e,{a:e}),e},i.d=function(t,e){if(Array.isArray(e))for(var r=0;r<e.length;){var n=e[r++],o=e[r++];i.o(t,n)?0===o&&r++:0===o?Object.defineProperty(t,n,{enumerable:!0,value:e[r++]}):Object.defineProperty(t,n,{enumerable:!0,get:o})}else for(var n in e)i.o(e,n)&&!i.o(t,n)&&Object.defineProperty(t,n,{enumerable:!0,get:e[n]})},i.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)};var a={};i.d(a,{default:function(){return y}});var u=i(944),s=i.n(u),c=i(512),f=i.n(c),p=(r=function(t,e){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r])})(t,e)},function(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}),h=f().seriesTypes.sma;function l(t,e,r,n,o){var i,a=null!=(i=e[r][n])?i:e[r];return o?(0,u.correctFloat)(t-a):(0,u.correctFloat)(t+a)}var d=function(t){function e(){return null!==t&&t.apply(this,arguments)||this}return p(e,t),e.prototype.getValues=function(t,e){var r,n,o,i,a,u,s=e.period,c=e.index,f=Math.floor(s/2+1),p=s+f,h=t.xData||[],d=t.yData||[],y=d.length,g=[],v=[],x=[],_=0;if(!(h.length<=p)){for(a=0;a<s-1;a++)_=l(_,d,a,c);for(u=0;u<=y-p;u++)o=u+s-1,i=u+p-1,_=l(_,d,o,c),n=(null!=(r=d[i][c])?r:d[i])-_/s,_=l(_,d,u,c,!0),g.push([h[i],n]),v.push(h[i]),x.push(n);return{values:g,xData:v,yData:x}}},e.defaultOptions=(0,u.merge)(h.defaultOptions,{params:{index:0,period:21}}),e}(h);(0,u.extend)(d.prototype,{nameBase:"DPO"}),f().registerSeriesType("dpo",d);var y=s();return a.default}()});