!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/mfi
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Money Flow Index indicator for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Grzegorz Blachliński
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/mfi",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/mfi"]=t(e._Highcharts,e._Highcharts.SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(e,t){return function(){"use strict";var r,n={512:function(e){e.exports=t},944:function(t){t.exports=e}},o={};function i(e){var t=o[e];if(void 0!==t)return t.exports;var r=o[e]={exports:{}};return n[e](r,r.exports,i),r.exports}i.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(t,{a:t}),t},i.d=function(e,t){if(Array.isArray(t))for(var r=0;r<t.length;){var n=t[r++],o=t[r++];i.o(e,n)?0===o&&r++:0===o?Object.defineProperty(e,n,{enumerable:!0,value:t[r++]}):Object.defineProperty(e,n,{enumerable:!0,get:o})}else for(var n in t)i.o(t,n)&&!i.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},i.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)};var u={};i.d(u,{default:function(){return g}});var s=i(944),a=i.n(s),c=i(512),f=i.n(c),p=(r=function(e,t){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)},function(e,t){function n(){this.constructor=e}r(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}),h=f().seriesTypes.sma;function l(e){return e.reduce(function(e,t){return e+t})}function d(e){return(e[1]+e[2]+e[3])/3}var y=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return p(t,e),t.prototype.getValues=function(e,t){var r,n,o,i,u,a,c,f=t.period,p=e.xData,h=e.yData,y=h?h.length:0,g=t.decimals,v=e.chart.get(t.volumeSeriesID),m=(null==v?void 0:v.getColumn("y"))||[],x=[],_=[],b=[],O=[],S=[],j=!1,w=1;if(!v)return void(0,s.error)("Series "+t.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,e.chart);if(!(p.length<=f)&&(0,s.isArray)(h[0])&&4===h[0].length&&m){for(n=d(h[w]);w<f+1;)o=n,j=(n=d(h[w]))>=o,i=n*m[w],O.push(j?i:0),S.push(j?0:i),w++;for(c=w-1;c<y;c++)c>w-1&&(O.shift(),S.shift(),o=n,j=(n=d(h[c]))>o,i=n*m[c],O.push(j?i:0),S.push(j?0:i)),u=l(S),r=100-100/(1+l(O)/u),a=parseFloat(r.toFixed(g)),x.push([p[c],a]),_.push(p[c]),b.push(a);return{values:x,xData:_,yData:b}}},t.defaultOptions=(0,s.merge)(h.defaultOptions,{params:{index:void 0,volumeSeriesID:"volume",decimals:4}}),t}(h);(0,s.extend)(y.prototype,{nameBase:"Money Flow Index"}),f().registerSeriesType("mfi",y);var g=a();return u.default}()});