!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/rsi
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Paweł Fus
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(t._Highcharts,t._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/rsi",["highcharts/highcharts"],function(t){return e(t,t.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/rsi"]=e(t._Highcharts,t._Highcharts.SeriesRegistry):t.Highcharts=e(t.Highcharts,t.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(t,e){return function(){"use strict";var r,n={512:function(t){t.exports=e},944:function(e){e.exports=t}},o={};function i(t){var e=o[t];if(void 0!==e)return e.exports;var r=o[t]={exports:{}};return n[t](r,r.exports,i),r.exports}i.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return i.d(e,{a:e}),e},i.d=function(t,e){if(Array.isArray(e))for(var r=0;r<e.length;){var n=e[r++],o=e[r++];i.o(t,n)?0===o&&r++:0===o?Object.defineProperty(t,n,{enumerable:!0,value:e[r++]}):Object.defineProperty(t,n,{enumerable:!0,get:o})}else for(var n in e)i.o(e,n)&&!i.o(t,n)&&Object.defineProperty(t,n,{enumerable:!0,get:e[n]})},i.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)};var a={};i.d(a,{default:function(){return y}});var s=i(944),u=i.n(s),c=i(512),f=i.n(c),p=(r=function(t,e){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r])})(t,e)},function(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}),h=f().seriesTypes.sma;function d(t,e){return parseFloat(t.toFixed(e))}var l=function(t){function e(){return null!==t&&t.apply(this,arguments)||this}return p(e,t),e.prototype.getValues=function(t,e){var r,n,o,i,a,u,c=e.period,f=t.xData,p=t.yData,h=p?p.length:0,l=e.decimals,y=[],g=[],v=[],b=0,x=0,m=e.index,_=1;if(!(f.length<c)){for((0,s.isNumber)(p[0])?u=p:(m=Math.min(m,p[0].length-1),u=p.map(function(t){return t[m]}));_<c;)(n=d(u[_]-u[_-1],l))>0?b+=n:x+=Math.abs(n),_++;for(o=d(b/(c-1),l),i=d(x/(c-1),l),a=_;a<h;a++)(n=d(u[a]-u[a-1],l))>0?(b=n,x=0):(b=0,x=Math.abs(n)),o=d((o*(c-1)+b)/c,l),r=0===(i=d((i*(c-1)+x)/c,l))?100:0===o?0:d(100-100/(1+o/i),l),y.push([f[a],r]),g.push(f[a]),v.push(r);return{values:y,xData:g,yData:v}}},e.defaultOptions=(0,s.merge)(h.defaultOptions,{params:{decimals:4,index:3}}),e}(h);f().registerSeriesType("rsi",l);var y=u();return a.default}()});