!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/tema
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Rafał Sebestjański
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/tema",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/tema"]=t(e._Highcharts,e._Highcharts.SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(e,t){return function(){"use strict";var r,n={512:function(e){e.exports=t},944:function(t){t.exports=e}},o={};function i(e){var t=o[e];if(void 0!==t)return t.exports;var r=o[e]={exports:{}};return n[e](r,r.exports,i),r.exports}i.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(t,{a:t}),t},i.d=function(e,t){if(Array.isArray(t))for(var r=0;r<t.length;){var n=t[r++],o=t[r++];i.o(e,n)?0===o&&r++:0===o?Object.defineProperty(e,n,{enumerable:!0,value:t[r++]}):Object.defineProperty(e,n,{enumerable:!0,get:o})}else for(var n in t)i.o(t,n)&&!i.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},i.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)};var l={};i.d(l,{default:function(){return v}});var s=i(944),a=i.n(s),u=i(512),c=i.n(u),p=(r=function(e,t){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)},function(e,t){function n(){this.constructor=e}r(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}),f=c().seriesTypes.ema,h=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return p(t,e),t.prototype.getEMA=function(t,r,n,o,i,l){return e.prototype.calculateEma.call(this,l||[],t,void 0===i?1:i,this.EMApercent,r,void 0===o?-1:o,n)},t.prototype.getTemaPoint=function(e,t,r,n){return[e[n-3],(0,s.correctFloat)(3*r.level1-3*r.level2+r.level3)]},t.prototype.getValues=function(t,r){var n,o,i,l,a=r.period,u=2*a,c=3*a,p=t.xData,f=t.yData,h=f?f.length:0,v=[],y=[],d=[],g=[],m=[],x={},_=-1,b=0,A=0;if(this.EMApercent=2/(a+1),!(h<3*a-2)){for((0,s.isArray)(f[0])&&(_=r.index?r.index:0),A=(b=e.prototype.accumulatePeriodPoints.call(this,a,_,f))/a,b=0,i=a;i<h+3;i++)i<h+1&&(x.level1=this.getEMA(f,n,A,_,i)[1],g.push(x.level1)),n=x.level1,i<u?b+=x.level1:(i===u&&(A=b/a,b=0),x.level1=g[i-a-1],x.level2=this.getEMA([x.level1],o,A)[1],m.push(x.level2),o=x.level2,i<c?b+=x.level2:(i===c&&(A=b/a),i===h+1&&(x.level1=g[i-a-1],x.level2=this.getEMA([x.level1],o,A)[1],m.push(x.level2)),x.level1=g[i-a-2],x.level2=m[i-2*a-1],x.level3=this.getEMA([x.level2],x.prevLevel3,A)[1],(l=this.getTemaPoint(p,c,x,i))&&(v.push(l),y.push(l[0]),d.push(l[1])),x.prevLevel3=x.level3));return{values:v,xData:y,yData:d}}},t.defaultOptions=(0,s.merge)(f.defaultOptions),t}(f);c().registerSeriesType("tema",h);var v=a();return l.default}()});