!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/wma
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Kacper Madej
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(t._Highcharts,t._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/wma",["highcharts/highcharts"],function(t){return e(t,t.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/wma"]=e(t._Highcharts,t._Highcharts.SeriesRegistry):t.Highcharts=e(t.Highcharts,t.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(t,e){return function(){"use strict";var r,n={512:function(t){t.exports=e},944:function(e){e.exports=t}},o={};function i(t){var e=o[t];if(void 0!==e)return e.exports;var r=o[t]={exports:{}};return n[t](r,r.exports,i),r.exports}i.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return i.d(e,{a:e}),e},i.d=function(t,e){if(Array.isArray(e))for(var r=0;r<e.length;){var n=e[r++],o=e[r++];i.o(t,n)?0===o&&r++:0===o?Object.defineProperty(t,n,{enumerable:!0,value:e[r++]}):Object.defineProperty(t,n,{enumerable:!0,get:o})}else for(var n in e)i.o(e,n)&&!i.o(t,n)&&Object.defineProperty(t,n,{enumerable:!0,get:e[n]})},i.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)};var u={};i.d(u,{default:function(){return g}});var a=i(944),s=i.n(a),c=i(512),f=i.n(c),p=(r=function(t,e){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r])})(t,e)},function(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}),h=f().seriesTypes.sma;function y(t,e,r,n,o){var i=e[n],u=o<0?r[n]:r[n][o];t.push([i,u])}function d(t,e,r,n){var o=t.length,i=t.reduce(function(t,e,r){return[null,t[1]+e[1]*(r+1)]})[1]/((o+1)/2*o),u=e[n-1];return t.shift(),[u,i]}var l=function(t){function e(){return null!==t&&t.apply(this,arguments)||this}return p(e,t),e.prototype.getValues=function(t,e){var r,n,o=e.period,i=t.xData,u=t.yData,s=u?u.length:0,c=i[0],f=[],p=[],h=[],l=1,g=-1,v=u[0];if(!(i.length<o)){(0,a.isArray)(u[0])&&(g=e.index,v=u[0][g]);for(var x=[[c,v]];l!==o;)y(x,i,u,l,g),l++;for(r=l;r<s;r++)n=d(x,i,u,r),f.push(n),p.push(n[0]),h.push(n[1]),y(x,i,u,r,g);return n=d(x,i,u,r),f.push(n),p.push(n[0]),h.push(n[1]),{values:f,xData:p,yData:h}}},e.defaultOptions=(0,a.merge)(h.defaultOptions,{params:{index:3,period:9}}),e}(h);f().registerSeriesType("wma",l);var g=s();return u.default}()});