!/**
 * Highstock JS v13.0.2 (2026-08-27)
 * @module highcharts/indicators/zigzag
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Kacper Madej
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/zigzag",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/zigzag"]=t(e._Highcharts,e._Highcharts.SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(e,t){return function(){"use strict";var r,n={512:function(e){e.exports=t},944:function(t){t.exports=e}},o={};function i(e){var t=o[e];if(void 0!==t)return t.exports;var r=o[e]={exports:{}};return n[e](r,r.exports,i),r.exports}i.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(t,{a:t}),t},i.d=function(e,t){if(Array.isArray(t))for(var r=0;r<t.length;){var n=t[r++],o=t[r++];i.o(e,n)?0===o&&r++:0===o?Object.defineProperty(e,n,{enumerable:!0,value:t[r++]}):Object.defineProperty(e,n,{enumerable:!0,get:o})}else for(var n in t)i.o(t,n)&&!i.o(e,n)&&Object.defineProperty(e,n,{enumerable:!0,get:t[n]})},i.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)};var a={};i.d(a,{default:function(){return g}});var s=i(944),u=i.n(s),h=i(512),p=i.n(h),c=(r=function(e,t){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)},function(e,t){function n(){this.constructor=e}r(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}),f=p().seriesTypes.sma,d=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return c(t,e),t.prototype.getValues=function(e,t){var r,n,o,i,a=t.lowIndex,s=t.highIndex,u=t.deviation/100,h={low:1+u,high:1-u},p=e.xData,c=e.yData,f=c?c.length:0,d=[],g=[],l=[],y=!1,v=!1;if(p&&!(p.length<=1)&&(!f||void 0!==c[0][a]&&void 0!==c[0][s])){var x=c[0][a],_=c[0][s];for(r=1;r<f;r++)c[r][a]<=_*h.high?(d.push([p[0],_]),o=[p[r],c[r][a]],i=!0,y=!0):c[r][s]>=x*h.low&&(d.push([p[0],x]),o=[p[r],c[r][s]],i=!1,y=!0),y&&(g.push(d[0][0]),l.push(d[0][1]),n=r++,r=f);for(r=n;r<f;r++)i?(c[r][a]<=o[1]&&(o=[p[r],c[r][a]]),c[r][s]>=o[1]*h.low&&(v=s)):(c[r][s]>=o[1]&&(o=[p[r],c[r][s]]),c[r][a]<=o[1]*h.high&&(v=a)),!1!==v&&(d.push(o),g.push(o[0]),l.push(o[1]),o=[p[r],c[r][v]],i=!i,v=!1);var m=d.length;return 0!==m&&d[m-1][0]<p[f-1]&&(d.push(o),g.push(o[0]),l.push(o[1])),{values:d,xData:g,yData:l}}},t.defaultOptions=(0,s.merge)(f.defaultOptions,{params:{index:void 0,period:void 0,lowIndex:2,highIndex:1,deviation:1}}),t}(f);(0,s.extend)(d.prototype,{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag"}),p().registerSeriesType("zigzag",d);var g=u();return a.default}()});